travis:
  secure:
    BINSTAR_TOKEN: WK274jUVEiz9CKPYK7k8Ny8wGC4uPhfRqn43t7+yUOfDT0FSrVJ9qy/nUFNye/37KFX1Sg9Cr1Qs7I3k5LyEzymL1p1MHLLmbVvpC9p3XPET7I1ULLJG28GYlZfE94mpB/VEiYghyCyxiw514bw/BS8Zua2HW/R3vKww7AMGutyOHORsPU+bUZCWqLTkxqtdQ0QVUv6Xen1tahK/e7914kNg8bqcD3EDDy8ugYwxWtGlcKiknwYHtJmXoU+KkEBDm5kd0t2em2po0WAG/tEE2PfcCd7afa2hYHQosvGr1s2WQva92bZjQ3AwJ1AmehVwudKscasPi1kVVkaxPRWO3hQWtRIl0oZv6x/IUQgcyVUmHuLG8aVzYGD3wYOPCwkGL8Js1fp2UezgjdhMUA98sVeqBMEN/ruj9xvbeLQ6vvYajCn4CNlhFYQFlicwKah2VlAJQX6fdPdqdwcvK/mCvDvoeQL1IzOgTEbk6fBItMXvG9rBSs1fqtq1VRtUaST/sxlbsbtFs79+ArG9CeQEfS56qrAyLWut0n68NcLhcgyyAeUiU3uqZzVvMQ6mdIwE0SmXPpdSGsKihZRla1P4ohHmyU6aw/jjsv57Zb5PhWC2kdQ82ChSEgyGdrXF02dV7scqD6H01XkOjivAatIfhQQRvKqE+rpaCwPLbUHmtfU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
